services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel build && pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT

